"""Add Contacts and Leads

Revision ID: 2429da4ad6d5
Revises: e90ba46c1364
Create Date: 2025-07-24 13:11:29.776189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2429da4ad6d5'
down_revision: Union[str, Sequence[str], None] = 'e90ba46c1364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
