"""Initial database setup

Revision ID: 6ee7282734ee
Revises: d8ba03190c9f
Create Date: 2025-08-08 12:57:03.990628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee7282734ee'
down_revision: Union[str, Sequence[str], None] = 'd8ba03190c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'notes')
    # ### end Alembic commands ###
