# """add role field to user

# Revision ID: 8d222aba1c26
# Revises: dadac73f5589
# Create Date: 2025-07-23 11:31:26.148590

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = '8d222aba1c26'
# down_revision: Union[str, Sequence[str], None] = 'dadac73f5589'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('role', sa.Enum('admin', 'manager', 'user', name='userrole'), nullable=True))
#     op.drop_column('users', 'is_admin')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
#     op.drop_column('users', 'role')
#     # ### end Alembic commands ###
from alembic import op
import sqlalchemy as sa
import enum

# Define the enum again
class UserRoleEnum(enum.Enum):
    admin = "admin"
    manager = "manager"
    user = "user"

# revision identifiers, used by Alembic.
revision = '8d222aba1c26'
down_revision = 'dadac73f5589'
branch_labels = None
depends_on = None

def upgrade():
    # Create ENUM type first
    userrole = sa.Enum('admin', 'manager', 'user', name='userrole')
    userrole.create(op.get_bind())  # CREATE TYPE userrole

    # Add column using the enum
    op.add_column('users', sa.Column('role', userrole, nullable=True))

def downgrade():
    # Drop the column first
    op.drop_column('users', 'role')

    # Then drop the enum type
    sa.Enum(name='userrole').drop(op.get_bind())
