"""add created_at to lead model

Revision ID: d8ba03190c9f
Revises: d84c27299aee
Create Date: 2025-08-07 13:14:54.101162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ba03190c9f'
down_revision: Union[str, Sequence[str], None] = 'd84c27299aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('user_search_idx'), table_name='users', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('user_search_idx'), 'users', [sa.literal_column("to_tsvector('english'::regconfig, (name::text || ' '::text) || email::text)")], unique=False, postgresql_using='gin')
    op.drop_column('leads', 'created_at')
    # ### end Alembic commands ###
