"""Make verification_token nullable

Revision ID: e90ba46c1364
Revises: fe8c134eda6a
Create Date: 2025-07-23 23:41:44.101495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90ba46c1364'
down_revision: Union[str, Sequence[str], None] = 'fe8c134eda6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verification_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verification_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
