"""Add source and status to contacts

Revision ID: f6cb78da36b1
Revises: b811e095f9df
Create Date: 2025-08-02 15:46:38.254112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6cb78da36b1'
down_revision: Union[str, Sequence[str], None] = 'b811e095f9df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('source', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'status')
    op.drop_column('contacts', 'source')
    # ### end Alembic commands ###
