"""password_reset_token added

Revision ID: fe8c134eda6a
Revises: 5754373602f2
Create Date: 2025-07-23 16:31:58.368527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8c134eda6a'
down_revision: Union[str, Sequence[str], None] = '5754373602f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['password_reset_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password_reset_token')
    # ### end Alembic commands ###
